spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: contacts_schema


logging.level.root: DEBUG

server:
  port: 8081
